# Generated by Django 5.2.1 on 2026-07-24 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_cropdetail_growth_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-msg_id'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterModelOptions(
            name='crop_recommend',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Crop Recommendation', 'verbose_name_plural': 'Crop Recommendations'},
        ),
        migrations.AlterModelOptions(
            name='cropdetail',
            options={'ordering': ['name'], 'verbose_name': 'Crop Detail', 'verbose_name_plural': 'Crop Details'},
        ),
    ]
