# Generated by Django 5.2.1 on 2026-07-24 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_contact_options_alter_crop_recommend_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.AlterModelOptions(
            name='crop_recommend',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cropdetail',
            options={},
        ),
    ]
